package commandbuilders.enums;

public enum UnitType { HUMAN, AI,
    COMODO_CHARGER, AZURE_HERALD, AZURITE_LION, FIRE_SPITTER, HAILSTONE_GOLEM,
    IRONCLIFF_GUARDIAN, PUREBLADE_ENFORCER, SILVERGUARD_KNIGHT,
    BLAZE_HOUND, BLOODSHARD_GOLEM, HAILSTONE_GOLEM_R, PLANAR_SCOUT, PYROMANCER,
    ROCK_PULVERISER, SERPENTI, WINDSHRIKE, ENTROPIC_DECAY, STAFF_OF_YKIR, TRUESTRIKE, SUNDROP_ELIXIR}

    //last four are the spells